version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - '8000:8000'
    networks:
      - app-network
    environment:
      - FLASK_ENV=development
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
    ports:
      - '3000:3000'
    networks:
      - app-network
    depends_on:
      - backend
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/usr/src/app

networks:
  app-network:

